# a mybinder.org-ready environment for demoing jupyterlab-tour
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   mamba env update --file binder/environment.yml
#   mamba activate jupyterlab-tour-demo
#
name: jupyterlab-tour-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python ==3.11.* #  binder needs a fairly weird pin, at present
  - jupyterlab >=4.0.5,<5
  - notebook >=7,<8
  # labextension build dependencies
  - hatch-jupyter-builder >=0.5
  - hatch-nodejs-version
  - hatchling >=1.5.0
  - nodejs >=18,<19
  - pip
  - python-build
